version: '3'
services:
  hospital_abm:
    build: ./docker
    image: hospital_abm
    volumes:
      - ./:/app
    working_dir: /app
    cap_add:
      - sys_ptrace
  notebook:
    build: ./docker
    volumes:
      - ./:/app
    working_dir: /app/
    ports:
      - "0.0.0.0:1111:8888"
    expose:
      - "8888"
    command: jupyter notebook --allow-root
